### ISSUE TITLE
Most examples are broken on the examples site

### ISSUE THREAD

**Issue by drone1** [zadvorsky/three.bas#61]
I'm getting errors on almost all examples. Complaints about OrbitControls; probably a simple fix:

```
root.js:56 Uncaught TypeError: THREE.OrbitControls is not a constructor
    at THREERoot.createOrbitControls (root.js:56:21)
    at new THREERoot (root.js:52:39)
    at init (main.js:4:14)
```

**Comment by thibka** [comment]
Made a [PR](https://github.com/zadvorsky/three.bas/pull/63) for that. If I'm not mistaken that's indeed a very simple fix

**Comment by drone1** [comment]
Thank you. Eagerly awaiting deployment of the site so I can check the examples :)

**Comment by thibka** [comment]
In the mean time, you can still run the project locally and replace
```html
<script src="https://unpkg.com/three/examples/js/controls/OrbitControls.js"></script>
```
by
```html
<script src="https://unpkg.com/three@0.144.0/examples/js/controls/OrbitControls.js"></script>
```
in the examples index.html files to avoid the issue
